---
html:
    css: styles.css
execute: 
  echo: false
  message: false
  warning: false
---
Hi, I'm Aashna, a rising junior at WTHS. I created this website through Kane's Data Science Bootcamp.


<div>
  <a href="mailto:aashnapatel2008@gmail.com" class="about-btn">
    Email
  </a>
  <a href="https://github.com/aashna-a-patel" class="about-btn">
    GitHub
  </a>
</div>

<style>
/* Custom styles for buttons */
.about-btn {
    background-color: #ff99b4;
    color: white;
    border: none;
    padding: 10px 20px;
    cursor: pointer;
    border-radius: 5px;
    transition: background-color 0.3s;
    text-decoration: none;
    display: inline-block;
}

.about-btn:hover {
    background-color: #eb547c;
    color: white;
}
</style>

## About This Website

This website provides insights into heart attack risk factors using data from Kaggle. We explore how age, cholesterol levels, chest pain types, and maximum heart rate influence heart attack risk.

### Tools and Libraries

- **R Programming Language**: For data analysis and visualization.
- **Libraries Used:**
  - `tidyverse`: For data manipulation and visualization.
  - `primer.data`: For data exploration.
  - `gganimate`: To create animated plots.
  - `brms`: For Bayesian regression modeling.
  - `readr`: For reading data files.
  - `gtsummary`: For summarizing data.
  - `transformr`: For animation support.
  - `ggplot2`: For creating static plots.
  - `dplyr`: For data manipulation.
  - `plotly`: For interactive visualizations.

### Data Source

The data for this analysis is sourced from Kaggle. You can view and download the dataset [here](https://www.kaggle.com/datasets/rashikrahmanpritom/heart-attack-analysis-prediction-dataset).

---

Thank you for visiting and exploring Cardiac Clues and Causes!

